version: 2

models:
  - name: people_summary
    description: "Aggregated summary of people by job title"
    columns:
      - name: job_title
        description: "Job title category"
        tests:
          - not_null
      - name: total_people
        description: "Number of people with this job title"
        tests:
          - not_null
      - name: avg_age
        description: "Average age of people with this job title"
        tests:
          - not_null

seeds:
  - name: orders
    description: "Raw order data"
    columns:
      - name: order_id
        tests:
          - not_null
          - unique
      - name: customer_id
        tests:
          - not_null
      - name: product_id
        tests:
          - not_null
      - name: order_date
        tests:
          - not_null

  - name: customers
    description: "Customer information"
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique
      - name: name
        tests:
          - not_null

  - name: products
    description: "Product catalog"
    columns:
      - name: product_id
        tests:
          - not_null
          - unique
      - name: category
        tests:
          - not_null

  - name: payments
    description: "Payment records"
    columns:
      - name: payment_id
        tests:
          - not_null
          - unique
      - name: order_id
        tests:
          - not_null
      - name: amount
        tests:
          - not_null